### ISSUE TITLE
Broken img tags in top-level page

### ISSUE THREAD

**Issue by robertlipe** [ale1800/YULC#2]
https://github.com/ale1800/YULC/tree/main?tab=readme-ov-file

links out to
https://github.com/ale1800/ESP32-board/assets/53172176/34b24297-1c93-43cd-b487-1ca270770319
and
https://github.com/ale1800/ESP32-board/assets/53172176/7c49a46b-c15e-45c9-bb84-2c160c00b566

...but those seem to not exist.

**Comment by ale1800** [comment]
Yes, I just dropped them in the readme file. I'll add all of them in folder
images

Il giorno ven 12 lug 2024 alle ore 19:17 Robert Lipe <
***@***.***> ha scritto:
