### ISSUE TITLE
WLED enabled?

### ISSUE THREAD

**Issue by Tim-The-Woodsman** [ale1800/YULC#3]
First and foremost: that thing is great, thank you! I'm doing stuff like this, but hillbilly style, bulky and ugly. I love this project! 

I'm just wondering if it'll be able to run WLED, I'm terribly lazy and my last FastLED project has been a while.

Love it ❤️

**Comment by ale1800** [comment]
Hello, thank you very much! Yes, it can run WLED. Officially, the ESP32-S3 is still in an experimental stage, however actually I'm still manually compiling some builds for the board and it seems to work quite well.

**Comment by Tim-The-Woodsman** [comment]
That's great ❤️ 

I'll take ten 😄
