### ISSUE TITLE
Faulty yulc controller?

### ISSUE THREAD

**Issue by heidepiek** [ale1800/YULC#6]
Got my yulc controller yesterday. Today I was going to mount it in the printed case and try it, but I run into a problem. The controller is not seen by the computer! Have all the drivers on the computer. Have tried multiple usb cables, even tried it on another pc. But the esp is not seen! If I take another esp32 s3 with the same cables and on both pc`s it is immediately recognized in the device manager. Also tried holding down the boot button when i plug the usb into the pc. Now it stops for me, tried everything. Faulty yulc controller?

Regards Harrie
![yulc-controller1](https://github.com/user-attachments/assets/49472de0-84fc-4981-b9d2-afe70a6fbe63)

![yulc-controller2](https://github.com/user-attachments/assets/ae33d66a-843c-408e-a998-af402a7a8bcf)

**Comment by ale1800** [comment]
Hi! Is your cable usb-A to usb-C? If yes, it's normal is not booting. Because you need a power delivery source. Do you see the green led on the board? Or only the red one?

**Comment by heidepiek** [comment]
Only the red one . It is a usb-A to usb-C cable i use. I only plugged the usb in and not another power source.

**Comment by ale1800** [comment]
> Only the red one . It is a usb-A to usb-C cable i use. I only plugged the usb in and not another power source. What do you mean by it needs a power delivery? I don`t have any leds attached. I thought i have to program it first.

Ok, that's why. As I said you have to use a usb-C to usb-C cable from a power delivery brick / laptop port to power it. If you only have usb-A you need to power the board with an external power supply and changing the jumper to "ext". In the [documentation](https://aaelectronics-docs.com/documentation/yulc/yulc.html) everything is explained if you need more information

**Comment by heidepiek** [comment]
Sorry alessandro, I don't want to destroy the board right away due to incompetence, so was a little careful with power connection . I have the board running.  Changed the pinout and voilla. This is new to me!  I thought I had to connect the usb and I can program it. So you can't take a regular usb charger of 2A and power the board through the usb (nor through the pc usb). I have a few phone chargers lying around with 1xusb-a and usb-c connection and and 2x usb-a. But that doesn't work. I now understand that if you want to program the board you have to power the board externally and then hook it up to your pc. I am going to read the documentation again. 

Greetz Harrie

**Comment by ale1800** [comment]
> This bit (Chargers with the USB-A output will not work, even selecting 5V on YULC. Only Type-C Power Delivery chargers are compatible). I did read it.   I  used this charger 
> ![usb charger](https://github.com/user-attachments/assets/ca27f712-5e17-4e26-a375-738565eec402) 
> It has a usb-a and a usb-c outlet. And this did not work, so i got stressed. But reading the documentation, it has to be possible to power the board with the usb connection but you have to use a decent powersupply with a usb-c connection. Now i get it! After i set the ext pin and added a powersupply  to the barrel it all worked. This board is well thought out. Again sorry alessandro. This dummy had read the documentation, but really thought the board could function on that little adapter. Unfortunately don't have a power supply lying around with a usb-c connection to try it. 
> 
> Harrie

Yes, so if you only have USB-A ports on your laptop you need the external power supply. But if your laptop already has a usb-C port, you can both power and program the board with it. Because 99% that port will handle the power delivery, even with only 5V. For example my laptop can't give anything more than 5V from it's usb-c, but those 5V are PD compatibile.
